@startuml
class Turn {
    - List<Move> moves
    - boolean isShot
    - double evaluation
    + Turn()
    + Turn(LinkedList<Move> moves, boolean isShot)
    + Turn(Turn currentTurn)
    + List<Move> getMoves()
    + void setMoves(List<Move> moves)
    + boolean isShot()
    + void setShot(boolean isShot)
    + double getEvaluation()
    + void setEvaluation(double evaluation)
    + void addMove(Move move)
    + void removeLastMove()
    + Move getLast()
    + boolean isEmpty()
    + static ArrayList<Turn> copyMovesToTurns(ArrayList<Move> moves)
}

Turn *-- Move
@enduml
